// <auto-generated />
using System;
using AssetTrackingCRUD2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetTrackingCRUD2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241205182636_SeedingAssetTable")]
    partial class SeedingAssetTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetTrackingCRUD2.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("brand");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchased_date");

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("asset_type").HasValue("asset_base");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            Country = "germany",
                            Model = "iPhone 12",
                            PurchasedDate = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "phone"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Dell",
                            Country = "germany",
                            Model = "XPS 13",
                            PurchasedDate = new DateTime(2021, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "computer"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            Country = "sweden",
                            Model = "Spectre x360",
                            PurchasedDate = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "computer"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Apple",
                            Country = "usa",
                            Model = "MacBook Air",
                            PurchasedDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "computer"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lenovo",
                            Country = "usa",
                            Model = "ThinkPad X1",
                            PurchasedDate = new DateTime(2022, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "computer"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Asus",
                            Country = "sweden",
                            Model = "ZenBook",
                            PurchasedDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "computer"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Samsung",
                            Country = "sweden",
                            Model = "Galaxy S21",
                            PurchasedDate = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "phone"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Google",
                            Country = "germany",
                            Model = "Pixel 5",
                            PurchasedDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "phone"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "OnePlus",
                            Country = "usa",
                            Model = "8T",
                            PurchasedDate = new DateTime(2022, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "phone"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Sony",
                            Country = "sweden",
                            Model = "Xperia 1 II",
                            PurchasedDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            asset_type = "phone"
                        });
                });

            modelBuilder.Entity("AssetTrackingCRUD2.Computer", b =>
                {
                    b.HasBaseType("AssetTrackingCRUD2.Asset");

                    b.HasDiscriminator().HasValue("computer");
                });

            modelBuilder.Entity("AssetTrackingCRUD2.Phone", b =>
                {
                    b.HasBaseType("AssetTrackingCRUD2.Asset");

                    b.HasDiscriminator().HasValue("phone");
                });

            modelBuilder.Entity("AssetTrackingCRUD2.Asset", b =>
                {
                    b.OwnsOne("AssetTrackingCRUD2.Price", "Price", b1 =>
                        {
                            b1.Property<int>("AssetId")
                                .HasColumnType("int");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price_value");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");

                            b1.HasData(
                                new
                                {
                                    AssetId = 1,
                                    Currency = "EUR",
                                    Value = 1020m
                                },
                                new
                                {
                                    AssetId = 2,
                                    Currency = "EUR",
                                    Value = 1500m
                                },
                                new
                                {
                                    AssetId = 3,
                                    Currency = "SEK",
                                    Value = 1400m
                                },
                                new
                                {
                                    AssetId = 4,
                                    Currency = "USD",
                                    Value = 1200m
                                },
                                new
                                {
                                    AssetId = 5,
                                    Currency = "USD",
                                    Value = 1600m
                                },
                                new
                                {
                                    AssetId = 6,
                                    Currency = "SEK",
                                    Value = 1300m
                                },
                                new
                                {
                                    AssetId = 7,
                                    Currency = "SEK",
                                    Value = 900m
                                },
                                new
                                {
                                    AssetId = 8,
                                    Currency = "EUR",
                                    Value = 700m
                                },
                                new
                                {
                                    AssetId = 9,
                                    Currency = "USD",
                                    Value = 600m
                                },
                                new
                                {
                                    AssetId = 10,
                                    Currency = "SEK",
                                    Value = 950m
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
